language: python

python:
  - "2.7"

env:
  matrix:
    - DJ="1.4.3" COPS="django-cacheops==1.0.2 --use-mirrors" DRF="djangorestframework==2.2.7"
    - DJ="1.4.3" COPS="django-cacheops==1.0.2 --use-mirrors" DRF="djangorestframework==2.3.6"
    - DJ="1.4.3" COPS="django-cacheops==1.0.2 --use-mirrors" DRF="djangorestframework==2.3.7"

    - DJ="1.5.1" COPS="django-cacheops==1.0.2 --use-mirrors" DRF="djangorestframework==2.2.7"
    - DJ="1.5.1" COPS="django-cacheops==1.0.2 --use-mirrors" DRF="djangorestframework==2.3.6"
    - DJ="1.5.1" COPS="django-cacheops==1.0.2 --use-mirrors" DRF="djangorestframework==2.3.7"

  global:
    - CI_ENABLED="1"

install:
  - pip install "django==$DJ --use-mirrors"
  - pip install $COPS
  - pip install $DRF
  - pip install -r requires-test.txt

  - pip install https://github.com/klem4/mockredis/archive/master.zip
  - export PYTHONPATH=.

script:
  - python test_project/manage.py test test_app