language: python

python:
  - "2.7.3"

env:
  matrix:
    - DJ="django==1.4.3 --use-mirrors"
    - DJ="django==1.5.2 --use-mirrors"
  global:
    - CI_ENABLED="1"

install:
  - pip install $DJ
  - pip install -r requires-test.txt

  - pip install https://github.com/klem4/mockredis/archive/master.zip
  - export PYTHONPATH=.

script:
  - python test_project/manage.py test test_app
